import { useState, useEffect, Suspense } from "react";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.scss";
import { Text, Button, Box, position } from "@chakra-ui/react";
import { Canvas, useThree } from "@react-three/fiber";
import { OrbitControls } from "@react-three/drei";
import Cake from "../models/Cake";

export default function Home() {
  return (
    <div className={styles.canvasContainer}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Canvas>
        <ambientLight intensity={0.1} />
        <pointLight position={[5, 0, -1]} intensity={0.5} />
        <pointLight position={[-4, 2, 3]} intensity={0.2} />
        <OrbitControls />
        <Suspense fallback={null}>
          <Cake position={[0, 0, 0]} scale={[18, 18, 18]} />
        </Suspense>
      </Canvas>
    </div>
  );
}
